IDOLS = [
    {"name":"Jennie","group":"BLACKPINK","agency":"YG","nationalities":["KR"],"dob":"16/01/1996","height":163,"roles":["rapper","vocal","visual"],"debut":2016,"members":4},
    {"name":"Jisoo","group":"BLACKPINK","agency":"YG","nationalities":["KR"],"dob":"03/01/1995","height":162,"roles":["vocal","visual","leader"],"debut":2016,"members":4},
    {"name":"Rosé","group":"BLACKPINK","agency":"YG","nationalities":["NZ","AU"],"dob":"11/02/1997","height":168,"roles":["vocal","dancer"],"debut":2016,"members":4},
    {"name":"Lisa","group":"BLACKPINK","agency":"YG","nationalities":["TH"],"dob":"27/03/1997","height":166,"roles":["rapper","dancer","visual","leader"],"debut":2016,"members":4},
    {"name":"Nayeon","group":"TWICE","agency":"JYP","nationalities":["KR"],"dob":"22/09/1995","height":163,"roles":["vocal","visual"],"debut":2015,"members":9},
    {"name":"Jeongyeon","group":"TWICE","agency":"JYP","nationalities":["KR"],"dob":"01/11/1996","height":167,"roles":["vocal"],"debut":2015,"members":9},
    {"name":"Momo","group":"TWICE","agency":"JYP","nationalities":["JP"],"dob":"09/11/1996","height":163,"roles":["dancer","rapper"],"debut":2015,"members":9},
    {"name":"Sana","group":"TWICE","agency":"JYP","nationalities":["JP"],"dob":"29/12/1996","height":163,"roles":["vocal","visual"],"debut":2015,"members":9},
    {"name":"Jihyo","group":"TWICE","agency":"JYP","nationalities":["KR"],"dob":"01/02/1997","height":160,"roles":["vocal","leader"],"debut":2015,"members":9},
    {"name":"Mina","group":"TWICE","agency":"JYP","nationalities":["JP","US"],"dob":"24/03/1997","height":163,"roles":["dancer","vocal","visual"],"debut":2015,"members":9},
    {"name":"Dahyun","group":"TWICE","agency":"JYP","nationalities":["KR"],"dob":"28/05/1998","height":159,"roles":["rapper","vocal"],"debut":2015,"members":9},
    {"name":"Chaeyoung","group":"TWICE","agency":"JYP","nationalities":["KR"],"dob":"23/04/1999","height":158,"roles":["rapper","vocal"],"debut":2015,"members":9},
    {"name":"Tzuyu","group":"TWICE","agency":"JYP","nationalities":["TW"],"dob":"14/06/1999","height":172,"roles":["dancer","visual"],"debut":2015,"members":9},
    {"name":"Irene","group":"Red Velvet","agency":"SM","nationalities":["KR"],"dob":"29/03/1991","height":158,"roles":["vocal","visual","leader"],"debut":2014,"members":5},
    {"name":"Seulgi","group":"Red Velvet","agency":"SM","nationalities":["KR"],"dob":"10/02/1994","height":160,"roles":["vocal","dancer","visual"],"debut":2014,"members":5},
    {"name":"Wendy","group":"Red Velvet","agency":"SM","nationalities":["KR","CA"],"dob":"21/02/1994","height":156,"roles":["vocal"],"debut":2014,"members":5},
    {"name":"Joy","group":"Red Velvet","agency":"SM","nationalities":["KR"],"dob":"03/09/1996","height":168,"roles":["vocal","visual"],"debut":2014,"members":5},
    {"name":"Yeri","group":"Red Velvet","agency":"SM","nationalities":["KR"],"dob":"05/03/1999","height":162,"roles":["vocal","rapper","visual"],"debut":2015,"members":5},
    {"name":"Winter","group":"aespa","agency":"SM","nationalities":["KR"],"dob":"01/01/2001","height":163,"roles":["vocal","dancer","visual"],"debut":2020,"members":4},
    {"name":"Karina","group":"aespa","agency":"SM","nationalities":["KR"],"dob":"11/04/2000","height":168,"roles":["dancer","rapper","visual","leader"],"debut":2020,"members":4},
    {"name":"Giselle","group":"aespa","agency":"SM","nationalities":["JP"],"dob":"30/10/2000","height":163,"roles":["rapper","vocal"],"debut":2020,"members":4},
    {"name":"Ningning","group":"aespa","agency":"SM","nationalities":["CN"],"dob":"23/10/2002","height":163,"roles":["vocal"],"debut":2020,"members":4},
    {"name":"Minji","group":"NewJeans","agency":"ADOR","nationalities":["KR"],"dob":"07/05/2004","height":171,"roles":["vocal","visual","leader"],"debut":2022,"members":5},
    {"name":"Hanni","group":"NewJeans","agency":"ADOR","nationalities":["AU","VN"],"dob":"06/10/2004","height":163,"roles":["vocal","dancer","visual"],"debut":2022,"members":5},
    {"name":"Danielle","group":"NewJeans","agency":"ADOR","nationalities":["AU","KR"],"dob":"11/04/2005","height":165,"roles":["vocal","visual"],"debut":2022,"members":5},
    {"name":"Haerin","group":"NewJeans","agency":"ADOR","nationalities":["KR"],"dob":"15/05/2006","height":163,"roles":["vocal","visual"],"debut":2022,"members":5},
    {"name":"Hyein","group":"NewJeans","agency":"ADOR","nationalities":["KR"],"dob":"21/04/2008","height":166,"roles":["dancer","visual","rapper"],"debut":2022,"members":5},
    {"name":"Wonyoung","group":"IVE","agency":"Starship","nationalities":["KR"],"dob":"31/08/2004","height":173,"roles":["vocal","visual","leader"],"debut":2021,"members":6},
    {"name":"Yujin","group":"IVE","agency":"Starship","nationalities":["KR"],"dob":"17/09/2003","height":170,"roles":["vocal","dancer"],"debut":2021,"members":6},
    {"name":"Gaeul","group":"IVE","agency":"Starship","nationalities":["KR"],"dob":"24/09/2002","height":166,"roles":["vocal","rapper"],"debut":2021,"members":6},
    {"name":"Rei","group":"IVE","agency":"Starship","nationalities":["JP"],"dob":"03/02/2004","height":163,"roles":["dancer","rapper","visual"],"debut":2021,"members":6},
    {"name":"Liz","group":"IVE","agency":"Starship","nationalities":["KR"],"dob":"21/11/2003","height":165,"roles":["vocal"],"debut":2021,"members":6},
    {"name":"Leeseo","group":"IVE","agency":"Starship","nationalities":["KR"],"dob":"21/02/2007","height":163,"roles":["dancer","visual"],"debut":2021,"members":6},
    {"name":"Sakura","group":"LE SSERAFIM","agency":"HYBE","nationalities":["JP"],"dob":"19/03/1998","height":164,"roles":["dancer","visual"],"debut":2022,"members":5},
    {"name":"Chaewon","group":"LE SSERAFIM","agency":"HYBE","nationalities":["KR"],"dob":"08/08/2000","height":158,"roles":["vocal","leader"],"debut":2022,"members":5},
    {"name":"Yunjin","group":"LE SSERAFIM","agency":"HYBE","nationalities":["KR","US"],"dob":"08/10/2001","height":168,"roles":["vocal"],"debut":2022,"members":5},
    {"name":"Kazuha","group":"LE SSERAFIM","agency":"HYBE","nationalities":["JP"],"dob":"31/08/2003","height":169,"roles":["dancer","visual"],"debut":2022,"members":5},
    {"name":"Eunchae","group":"LE SSERAFIM","agency":"HYBE","nationalities":["KR"],"dob":"02/12/2006","height":172,"roles":["dancer","visual","rapper"],"debut":2022,"members":5},
    {"name":"Sullyoon","group":"NMIXX","agency":"JYP","nationalities":["KR"],"dob":"28/12/2003","height":170,"roles":["vocal","visual"],"debut":2022,"members":6},
    {"name":"Bae","group":"NMIXX","agency":"JYP","nationalities":["KR","US"],"dob":"22/11/2002","height":163,"roles":["vocal","rapper"],"debut":2022,"members":6},
    {"name":"Haewon","group":"NMIXX","agency":"JYP","nationalities":["KR"],"dob":"25/07/2001","height":163,"roles":["vocal","leader"],"debut":2022,"members":6},
    {"name":"Lily","group":"NMIXX","agency":"JYP","nationalities":["AU"],"dob":"26/09/2002","height":165,"roles":["vocal"],"debut":2022,"members":6},
    {"name":"Kyujin","group":"NMIXX","agency":"JYP","nationalities":["KR"],"dob":"24/11/2005","height":165,"roles":["dancer","rapper","visual"],"debut":2022,"members":6},
    {"name":"Yeji","group":"ITZY","agency":"JYP","nationalities":["KR"],"dob":"26/05/2000","height":165,"roles":["dancer","rapper","visual","leader"],"debut":2019,"members":5},
    {"name":"Lia","group":"ITZY","agency":"JYP","nationalities":["KR","US"],"dob":"21/07/2000","height":163,"roles":["vocal"],"debut":2019,"members":5},
    {"name":"Ryujin","group":"ITZY","agency":"JYP","nationalities":["KR"],"dob":"17/04/2001","height":163,"roles":["dancer","rapper","visual"],"debut":2019,"members":5},
    {"name":"Chaeryeong","group":"ITZY","agency":"JYP","nationalities":["KR"],"dob":"05/06/2001","height":168,"roles":["dancer","vocal"],"debut":2019,"members":5},
    {"name":"Yuna","group":"ITZY","agency":"JYP","nationalities":["KR"],"dob":"09/12/2003","height":170,"roles":["dancer","visual","rapper"],"debut":2019,"members":5},
]
