IDOLS = [
    {"name":"Jennie","group":"BLACKPINK","agency":"YG","country":"KR","age":28,"debut":2016,"members":4},
    {"name":"Jisoo","group":"BLACKPINK","agency":"YG","country":"KR","age":29,"debut":2016,"members":4},
    {"name":"Rosé","group":"BLACKPINK","agency":"YG","country":"NZ","age":27,"debut":2016,"members":4},
    {"name":"Lisa","group":"BLACKPINK","agency":"YG","country":"TH","age":27,"debut":2016,"members":4},
    {"name":"Nayeon","group":"TWICE","agency":"JYP","country":"KR","age":30,"debut":2015,"members":9},
    {"name":"Jeongyeon","group":"TWICE","agency":"JYP","country":"KR","age":29,"debut":2015,"members":9},
    {"name":"Momo","group":"TWICE","agency":"JYP","country":"JP","age":29,"debut":2015,"members":9},
    {"name":"Sana","group":"TWICE","agency":"JYP","country":"JP","age":29,"debut":2015,"members":9},
    {"name":"Jihyo","group":"TWICE","agency":"JYP","country":"KR","age":28,"debut":2015,"members":9},
    {"name":"Mina","group":"TWICE","agency":"JYP","country":"JP","age":28,"debut":2015,"members":9},
    {"name":"Dahyun","group":"TWICE","agency":"JYP","country":"KR","age":27,"debut":2015,"members":9},
    {"name":"Chaeyoung","group":"TWICE","agency":"JYP","country":"KR","age":26,"debut":2015,"members":9},
    {"name":"Tzuyu","group":"TWICE","agency":"JYP","country":"TW","age":25,"debut":2015,"members":9},
    {"name":"Irene","group":"Red Velvet","agency":"SM","country":"KR","age":31,"debut":2014,"members":5},
    {"name":"Seulgi","group":"Red Velvet","agency":"SM","country":"KR","age":30,"debut":2014,"members":5},
    {"name":"Wendy","group":"Red Velvet","agency":"SM","country":"KR","age":30,"debut":2014,"members":5},
    {"name":"Joy","group":"Red Velvet","agency":"SM","country":"KR","age":28,"debut":2014,"members":5},
    {"name":"Yeri","group":"Red Velvet","agency":"SM","country":"KR","age":25,"debut":2015,"members":5},
    {"name":"Winter","group":"aespa","agency":"SM","country":"KR","age":24,"debut":2020,"members":4},
    {"name":"Karina","group":"aespa","agency":"SM","country":"KR","age":24,"debut":2020,"members":4},
    {"name":"Giselle","group":"aespa","agency":"SM","country":"JP","age":24,"debut":2020,"members":4},
    {"name":"Ningning","group":"aespa","agency":"SM","country":"CN","age":22,"debut":2020,"members":4},
    {"name":"Minji","group":"NewJeans","agency":"ADOR","country":"KR","age":20,"debut":2022,"members":5},
    {"name":"Hanni","group":"NewJeans","agency":"ADOR","country":"AU","age":20,"debut":2022,"members":5},
    {"name":"Danielle","group":"NewJeans","agency":"ADOR","country":"AU","age":20,"debut":2022,"members":5},
    {"name":"Haerin","group":"NewJeans","agency":"ADOR","country":"KR","age":19,"debut":2022,"members":5},
    {"name":"Hyein","group":"NewJeans","agency":"ADOR","country":"KR","age":17,"debut":2022,"members":5},
    {"name":"Wonyoung","group":"IVE","agency":"Starship","country":"KR","age":21,"debut":2021,"members":6},
    {"name":"Yujin","group":"IVE","agency":"Starship","country":"KR","age":21,"debut":2021,"members":6},
    {"name":"Gaeul","group":"IVE","agency":"Starship","country":"KR","age":23,"debut":2021,"members":6},
    {"name":"Rei","group":"IVE","agency":"Starship","country":"JP","age":20,"debut":2021,"members":6},
    {"name":"Liz","group":"IVE","agency":"Starship","country":"KR","age":21,"debut":2021,"members":6},
    {"name":"Leeseo","group":"IVE","agency":"Starship","country":"KR","age":19,"debut":2021,"members":6},
    {"name":"Sakura","group":"LE SSERAFIM","agency":"HYBE","country":"JP","age":27,"debut":2022,"members":5},
    {"name":"Chaewon","group":"LE SSERAFIM","agency":"HYBE","country":"KR","age":24,"debut":2022,"members":5},
    {"name":"Yunjin","group":"LE SSERAFIM","agency":"HYBE","country":"KR","age":24,"debut":2022,"members":5},
    {"name":"Kazuha","group":"LE SSERAFIM","agency":"HYBE","country":"JP","age":22,"debut":2022,"members":5},
    {"name":"Eunchae","group":"LE SSERAFIM","agency":"HYBE","country":"KR","age":19,"debut":2022,"members":5},
    {"name":"Sullyoon","group":"NMIXX","agency":"JYP","country":"KR","age":22,"debut":2022,"members":7},
    {"name":"Bae","group":"NMIXX","agency":"JYP","country":"KR","age":22,"debut":2022,"members":7},
    {"name":"Haewon","group":"NMIXX","agency":"JYP","country":"KR","age":23,"debut":2022,"members":7},
    {"name":"Lily","group":"NMIXX","agency":"JYP","country":"AU","age":22,"debut":2022,"members":7},
    {"name":"Kyujin","group":"NMIXX","agency":"JYP","country":"KR","age":20,"debut":2022,"members":7},
    {"name":"Jinni","group":"NMIXX","agency":"JYP","country":"KR","age":22,"debut":2022,"members":7},
    {"name":"Jiwoo","group":"NMIXX","agency":"JYP","country":"KR","age":24,"debut":2022,"members":7},
    {"name":"Yeji","group":"ITZY","agency":"JYP","country":"KR","age":25,"debut":2019,"members":5},
    {"name":"Lia","group":"ITZY","agency":"JYP","country":"KR","age":24,"debut":2019,"members":5},
    {"name":"Ryujin","group":"ITZY","agency":"JYP","country":"KR","age":24,"debut":2019,"members":5},
    {"name":"Chaeryeong","group":"ITZY","agency":"JYP","country":"KR","age":24,"debut":2019,"members":5},
    {"name":"Yuna","group":"ITZY","agency":"JYP","country":"KR","age":22,"debut":2019,"members":5},
]
